import type { Language } from '@/lib/i18n';

const SKILLS_PT = [
  'Atendimento ao cliente',
  'Comunicação',
  'Trabalho em equipa',
  'Liderança',
  'Gestão de tempo',
  'Resolução de problemas',
  'Microsoft Word',
  'Microsoft Excel',
  'Microsoft PowerPoint',
  'Outlook',
  'Gestão de stock',
  'Armazém',
  'Logística',
  'Empilhador',
  'Motorista (categoria B)',
  'Cuidados a idosos',
  'Cuidados infantis',
  'Serviço doméstico',
  'Cozinha',
  'Pastelaria',
  'Limpeza',
  'Manutenção predial',
  'Eletricidade (baixa tensão)',
  'Canalização',
  'Pintura',
  'Soldadura',
  'Informática básica',
  'Redes sociais',
  'Programação',
  'Contabilidade básica',
  'Faturação',
  'Caixa / TPA',
  'Vendas',
  'Marketing digital',
  'Apoio administrativo',
  'Recursos humanos',
  'Primeiros socorros',
  'Higiene e segurança no trabalho',
  'Introdução de dados',
  'Controlo de qualidade',
  'Costura',
  'Cabeleireiro',
  'Jardinagem',
  'Operação de máquinas',
];

const SKILLS_EN = [
  'Customer service',
  'Communication',
  'Teamwork',
  'Leadership',
  'Time management',
  'Problem solving',
  'Microsoft Word',
  'Microsoft Excel',
  'Microsoft PowerPoint',
  'Outlook',
  'Stock management',
  'Warehouse',
  'Logistics',
  'Forklift operation',
  'Driving (category B)',
  'Elderly care',
  'Childcare',
  'Housekeeping',
  'Kitchen',
  'Bakery',
  'Cleaning',
  'Building maintenance',
  'Electrical (low voltage)',
  'Plumbing',
  'Painting',
  'Welding',
  'Basic IT',
  'Social media',
  'Programming',
  'Basic accounting',
  'Invoicing',
  'Cash register / POS',
  'Sales',
  'Digital marketing',
  'Administrative support',
  'Human resources',
  'First aid',
  'Workplace health and safety',
  'Data entry',
  'Quality control',
  'Sewing',
  'Hairdressing',
  'Gardening',
  'Machine operation',
];

const SKILLS_ES = [
  'Atención al cliente',
  'Comunicación',
  'Trabajo en equipo',
  'Liderazgo',
  'Gestión del tiempo',
  'Resolución de problemas',
  'Microsoft Word',
  'Microsoft Excel',
  'Microsoft PowerPoint',
  'Outlook',
  'Gestión de stock',
  'Almacén',
  'Logística',
  'Carretilla elevadora',
  'Conducción (categoría B)',
  'Cuidado de mayores',
  'Cuidado infantil',
  'Servicio doméstico',
  'Cocina',
  'Repostería',
  'Limpieza',
  'Mantenimiento de edificios',
  'Electricidad (baja tensión)',
  'Fontanería',
  'Pintura',
  'Soldadura',
  'Informática básica',
  'Redes sociales',
  'Programación',
  'Contabilidad básica',
  'Facturación',
  'Caja / TPV',
  'Ventas',
  'Marketing digital',
  'Apoyo administrativo',
  'Recursos humanos',
  'Primeros auxilios',
  'Higiene y seguridad en el trabajo',
  'Introducción de datos',
  'Control de calidad',
  'Costura',
  'Peluquería',
  'Jardinería',
  'Operación de máquinas',
];

const LANGUAGES_PT = [
  'Português',
  'Português (língua materna)',
  'Inglês',
  'Espanhol',
  'Francês',
  'Alemão',
  'Italiano',
  'Russo',
  'Mandarim',
  'Hindi',
  'Árabe',
  'Neerlandês (holandês)',
  'Polaco',
  'Romeno',
  'Ucraniano',
  'Crioulo cabo-verdiano',
  'Língua gestual portuguesa',
  'Grego',
  'Sueco',
  'Norueguês',
  'Dinamarquês',
  'Tailandês',
  'Vietnamita',
  'Japonês',
  'Coreano',
];

const LANGUAGES_EN = [
  'Portuguese',
  'Portuguese (native)',
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Russian',
  'Mandarin',
  'Hindi',
  'Arabic',
  'Dutch',
  'Polish',
  'Romanian',
  'Ukrainian',
  'Cape Verdean Creole',
  'Portuguese Sign Language',
  'Greek',
  'Swedish',
  'Norwegian',
  'Danish',
  'Thai',
  'Vietnamese',
  'Japanese',
  'Korean',
];

const LANGUAGES_ES = [
  'Portugués',
  'Portugués (lengua materna)',
  'Inglés',
  'Español',
  'Francés',
  'Alemán',
  'Italiano',
  'Ruso',
  'Mandarín',
  'Hindi',
  'Árabe',
  'Neerlandés (holandés)',
  'Polaco',
  'Rumano',
  'Ucraniano',
  'Criollo caboverdiano',
  'Lengua de signos portuguesa',
  'Griego',
  'Sueco',
  'Noruego',
  'Danés',
  'Tailandés',
  'Vietnamita',
  'Japonés',
  'Coreano',
];

export function getCurriculumSkillSuggestions(lang: Language): string[] {
  if (lang === 'en') return SKILLS_EN;
  if (lang === 'es') return SKILLS_ES;
  return SKILLS_PT;
}

export function getCurriculumLanguageSuggestions(lang: Language): string[] {
  if (lang === 'en') return LANGUAGES_EN;
  if (lang === 'es') return LANGUAGES_ES;
  return LANGUAGES_PT;
}
